### ISSUE TITLE
Draco Decoder CDN gives 404

### ISSUE THREAD

**Issue by JoshuaeKaiser** [google/draco#970] opened 2023-02-01 16:55 UTC
All CDNs from the draco decoder seem to have gone dark. Do we have a new CDN or atleast a pointer to the code so I can get my app working again ?

**Comment by JoshuaeKaiser** [comment] 2023-02-01 17:35
Hi @FrankGalligan thank you for your response. Thats weird, only 2 I know of are below and i get 404 from both.

https://www.gstatic.com/draco/v1/decoders/
https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/js/libs/draco/

**Comment by ondys** [comment] 2023-02-01 17:57
You need to address a specific file, e.g.:
https://www.gstatic.com/draco/v1/decoders/draco_decoder.js

**Comment by FrankGalligan** [comment] 2023-02-01 18:09
I just checked that link and all of the others. And I don't have an issue. I got the file with a 200.

@JoshuaeKaiser What is the specific URL you are getting 404 from?

**Comment by JoshuaeKaiser** [comment] 2023-02-01 18:19
@FrankGalligan i get 404 to those URLs i shared. 

<img width="1792" alt="Screenshot 2023-02-01 at 18 14 51" src="https://user-images.githubusercontent.com/17850490/216128076-23ddaaed-4941-450d-8935-e9e647752cea.png">

For context im suing this with THREE JS. Specifically with the dracoLoader.setDecoderPath() method.

@ondys i do have access to the URL you shared, but that doesn't seem a substitution for what I was using before. the URL seems to get concatinated with a partial url "draco_decoder.wasm" 

like so:

https://www.gstatic.com/draco/v1/decoders/draco_decoder.jsdraco_decoder.wasm 404

Thanks for your help guys!

**Comment by JoshuaeKaiser** [comment] 2023-02-02 09:34
@FrankGalligan you are right and that is how I had it before, but as I say this URL below now returns a 404...

https://www.gstatic.com/draco/v1/decoders/

**Comment by FrankGalligan** [comment] 2023-02-02 18:02
@JoshuaeKaiser Yeah this exact URL
https://www.gstatic.com/draco/v1/decoders/
will return a 404. That is working as intended. 

You need to explicitly specify the URL to get the different files. E.g.
https://www.gstatic.com/draco/v1/decoders/draco_decoder.wasm

But for the code in DRACOLoader.js it wants the URL path to the directory where the draco decoder files are stored, because it will then pull the files explicitly. 

Does it work in your app now?

**Comment by FrankGalligan** [comment] 2023-02-09 22:23
Closing for now. If you are still having issues, please re-open.

Thanks

**Closed by FrankGalligan** 2023-02-09 22:23 UTC
