### ISSUE TITLE
Segmentation Fault in encoding obj file

### ISSUE THREAD

**Issue by Center-Stage** [google/draco#651] opened 2020-12-02 08:23 UTC
Hi, I am getting a segmentation fault in encoding a specific obj file. With most of the obj file I am getting the expected result but for the some obj files with format as attached gives segmentation fault. Following is the link to the obj file https://drive.google.com/file/d/1IKVBH5K3UARacJmjcAkoHO1Fomqawrzs/view?usp=sharing

**Comment by FrankGalligan** [comment] 2020-12-02 17:26
Duplicate of #652

**Closed** 2020-12-02 17:26 UTC
