### ISSUE TITLE
"Undefined symbols for architecture arm64:" M1 Mac Draco 1.3.5

### ISSUE THREAD

**Issue by felixshing** [google/draco#957] opened 2022-12-15 06:41 UTC
Hello, when I try to make my project on my M1 Pro mac with Draco 1.3.5. It shows the following error. How could I fix it?

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/61814345/207787797-62596a3a-ae69-4052-b7f3-e1ca11be8ab0.png">

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/61814345/207790735-965c7e46-457a-4225-97ef-6ef7edcf2e96.png">

**Comment by tomfinegan** [comment] 2022-12-15 21:11
What host is the build running on, and for which target are you compiling?

The error looks like you built an x86_64 draco and tried to link it into an arm64 binary. That will not work. You need to update one of your configurations. 

One way to do this is to set `CMAKE_OSX_ARCHITECTURES` to arm64;x86_64 when building Draco to build a universal library with both configs.

Closing as invalid. This config is confirmed to work on M1 mac.

**Closed by tomfinegan** 2022-12-15 21:11 UTC
