### ISSUE TITLE
 about draco_decoder.js decod  2.5 million points error

### ISSUE THREAD

**Issue by openforus** [google/draco#56] opened 2017-02-07 07:15 UTC
I used compression tools draco_encoder.exe to compress a model, no problem, but when I unpacked it with draco_examples use draco_decoder.js,  The error occurred as follows

![dracoerror](https://cloud.githubusercontent.com/assets/18387798/22680847/3b5a3088-ed45-11e6-9768-b31e2fd6244b.jpg)
Compressed model file：
[http://pan.baidu.com/s/1cMkXcy](url)

**Comment by ondys** [comment] 2017-02-07 20:05
What browser / OS did you use? I tried to load the attached model on Chrome Browser (55.0.2883.87 (64-bit)) running on Ubuntu 14.04 and I could not reproduce the issue (the model loaded without problems). So the problem may be something browser-specific.

**Comment by openforus** [comment] 2017-02-08 01:25
thanks, it may be Chrome Browser version problem，I will update my Chrome Browser and check it.

**Comment by openforus** [comment] 2017-02-08 06:13
I had check again,it also the some problem,my  Chrome Browser version is 56.0.2924.87 32bit .
my os is wind10 .when open in edge it is ok but  use about 1.3G memory，so maybe it is the browser protection policy in Chrome 32bit.

**Comment by ondys** [comment] 2017-02-08 19:01
Yes it may be a memory issue with 32 bit browsers. If possible, please try it on a 64-bit version. We will try to investigate it more on our end as well. Thanks for the update.

**Comment by FrankGalligan** [comment] 2018-08-04 17:45
I'm closing this issue. If you are still having problems please re-open.

**Closed by FrankGalligan** 2018-08-04 17:45 UTC
