### ISSUE TITLE
Can't Build Draco on VS2017 on Win10 x64.

### ISSUE THREAD

**Issue by SabreRunner** [google/draco#163] opened 2017-08-03 12:09 UTC
I've downloaded CMake and followed the directions but I'm getting errors in building, invalid characters from line 2 of the make file.

**Comment by tomfinegan** [comment] 2017-08-03 13:39
I'm unable to reproduce this. Please include your CMake command line, and attach the following files from the directory where you ran CMake:

CMakeCache.txt
CMakeFiles/CMakeOutput.log

Thanks!

**Comment by tomfinegan** [comment] 2017-08-03 14:34
Odd-- those are nearly empty. Can you also include CMakeFiles/CMakeError.log and all console output from the CMake run? Thanks!

**Comment by SabreRunner** [comment] 2017-08-03 14:39
`C:\GaliguTest\Draco>cmake . -G "Visual Studio 15 2017 Win64"
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.1.548.43366
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 2017-08-03 17:38:25.
    Project "C:\GaliguTest\Draco\CMakeFiles\3.9.0\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(90,5): error MSB4184: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation(Windows, 10.0.14393.0)" cannot be evaluated. Illegal characters in path. [C:\GaliguTest\Draco\CMakeFiles\3.9.0\VCTargetsPath.vcxproj]
    Done Building Project "C:\GaliguTest\Draco\CMakeFiles\3.9.0\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\GaliguTest\Draco\CMakeFiles\3.9.0\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(90,5): error MSB4184: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation(Windows, 10.0.14393.0)" cannot be evaluated. Illegal characters in path. [C:\GaliguTest\Draco\CMakeFiles\3.9.0\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.66


  Exit code: 1



-- Configuring incomplete, errors occurred!`

And I don't see and error.log.

**Comment by tomfinegan** [comment] 2017-08-03 15:42
Try doing the following from a normal command (not in a Visual Studio command prompt).

1. Make sure you have any local edits committed, then run this command at the root of the Draco repository:
git clean -fddx

2. From a directory that is **not** within draco repository, run the command:
cmake path/to/draco -G "Visual Studio 15 2017 Win64"

Does that make any difference?

**Comment by oscarbg** [comment] 2017-08-03 17:09
Hi,
just was going to open an issue similar to this..I build with Cmake-GUI:
configure step ok..
generate fails..

seeing log 
the fails are
"CMake Error: CMake can not determine linker language for target:"
for targets that only include header files..

Full log:

The C compiler identification is MSVC 19.10.25019.0
The CXX compiler identification is MSVC 19.10.25019.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find Git (missing: GIT_EXECUTABLE) 
Could NOT find Git (missing: GIT_EXECUTABLE) 
Configuring done
CMake Error: CMake can not determine linker language for target: draco_compression_attributes_pred_schemes_dec
CMake Error: CMake can not determine linker language for target: draco_enc_config
CMake Error: CMake can not determine linker language for target: draco_dec_config
Generating done

**Comment by tomfinegan** [comment] 2017-08-03 17:18
@oscarbg 
That's a different issue, and already fixed. See https://github.com/google/draco/issues/162

**Comment by SabreRunner** [comment] 2017-08-04 02:54
Thank you very much for helping, Tom. I tried what you said.
Still no difference, though. :(

**Comment by tomfinegan** [comment] 2017-08-04 17:24
@SabreRunner 
I'm not certain what's going on-- the error you're seeing is coming from MSBuild during parse of a Visual Studio built in project file, and isn't something I'm able to reproduce (with multiple combinations of cmake and MSVC releases).

Some questions that might help figure out what's going on:
1) Do you have the platform SDK installed?
2) Can you compile a simple C++ test program in Visual Studio? 

The error about an invalid character sounds like nonsense, but maybe it's because an empty string is being returned when the query for the platform SDK path runs. If the answer to number 1 and number 2 is yes, please try this basic test.

1. Download this [paste](https://pastebin.mozilla.org/9028870) and save it as hello.cc
2. Download this [paste](https://pastebin.mozilla.org/9028868) to the same directory and save it as CMakeLists.txt
3. Run cmake in that directory. (the way you've been running it, `cmake . -G "Visual Studio 15 2017 Win64"` should be fine)
4. Post the output here.

**Comment by SabreRunner** [comment] 2017-08-05 09:12
You are absolutely correct. I'm getting the same error. So the problem is with me. :(
What can I do?
`CMake Error at CMakeLists.txt:1 (project):
  Failed to run MSBuild command:

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.1.548.43366
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 2017-08-05 12:10:29.
    Project "C:\Hello\CMakeFiles\3.9.0\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(90,5): error MSB4184: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation(Windows, 10.0.14393.0)" cannot be evaluated. Illegal characters in path. [C:\Hello\CMakeFiles\3.9.0\VCTargetsPath.vcxproj]
    Done Building Project "C:\Hello\CMakeFiles\3.9.0\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Hello\CMakeFiles\3.9.0\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(90,5): error MSB4184: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation(Windows, 10.0.14393.0)" cannot be evaluated. Illegal characters in path. [C:\Hello\CMakeFiles\3.9.0\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.73


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Hello/CMakeFiles/CMakeOutput.log".`

**Comment by tomfinegan** [comment] 2017-08-07 16:31
It sounds like your MSVC install is incomplete or partially broken. I would rerun the installer and double check that all "Visual C++" components are installed. You might also be able to find options for "C++ compiler tools" and "Windows Platform SDK" within the installer (the names should be similar, but I'm probably not recalling them completely correctly-- haven't gone through the install in a while and the names are fuzzy memories).

If all else fails, completely remove Microsoft Visual Studio and reinstall it while making sure anything looking vaguely like C++ support is installed.

Closing this since there's nothing that can be done from the draco side.

**Closed by tomfinegan** 2017-08-07 16:31 UTC
