### ISSUE TITLE
Large mesh can't be decoded when using MESH_SEQUENTIAL_ENCODING

### ISSUE THREAD

**Issue by SunnyBily** [google/draco#798] opened 2022-01-26 02:22 UTC
Hello,
I use the draco::Encoder API to generate the draco document. I build the draco::Mesh by TriangleSoupMeshBuilder. And I set the quantization of position, normal, tex_coord and generic to 15, 8, 8 and 8, respectively. I want the faces to stay in order, so I set encoding method MESH_SEQUENTIAL_ENCODING. 
It works good when the mesh is small. But  when the mesh is large, some problems occuered. I have try to decoded the mesh with 2 million points and 1.7 million faces. There is no problem if I don't use MESH_SEQUENTIAL_ENCODING option. But When I use it, compressed document can't be decoded. 
I tried to find the problem by debugging the source code. Here is the first index of faces of the mesh I want to compress. 
![企业微信截图_16431640001109](https://user-images.githubusercontent.com/36740211/151093717-197470b4-aec3-4248-a4b6-8e59b6fd5e64.png)
Here is the first index of faces after decoding when I debugging draco_decoder.
![企业微信截图_16431640243293](https://user-images.githubusercontent.com/36740211/151093729-0fbb7f47-e0e1-4703-bd1f-6d59c1d7f28d.png)
It can be found that the decoded value is completely incorrect. 
Did I make mistakes when i use API? Or is it a bug?

Thank you for your help.

**Comment by ondys** [comment] 2022-01-26 03:21
I believe it may be caused by a bug that we recently fixed internally. Please try it again with the following PR: https://github.com/google/draco/pull/799

**Comment by SunnyBily** [comment] 2022-01-28 02:14
Thank you very much. The program can run normally after I modify it according to the code you submitted. When will the next version be released?

**Comment by ondys** [comment] 2022-01-28 02:24
The PR has been merged already. If you need Javascript or WASM decoders, we will most likely update them in near future (most likely next week).

**Closed** 2022-02-11 09:31 UTC
