### ISSUE TITLE
Possible memory leak in DRACOLoader.js

### ISSUE THREAD

**Issue by simena86** [google/draco#312] opened 2017-12-04 14:39 UTC
I'm using DRACOLoader.js to load draco files (files holds meshes encoded from .obj files):

``` javascript
const dracoLoader = new THREE.DRACOLoader('<url-to-gcs-bucket-with warm decoder>');
dracoLoader.setVerbosity(1);
dracoLoader.setCrossOrigin('anonymous');

...
let mesh = null;
let scene = null;

// initialize three.js scene
...

function loadMesh() {
    dracoLoader.load('<url to drc file>', function(bufferGeometry) {
        const material = new THREE.MeshPhongMaterial({
                    color: 0x996633,
                    specular: 0x050505,
                    shininess: 100
          });
        
          mesh = new THREE.Mesh(bufferGeometry, material);
          scene.add(mesh)
    })
}

function closeViewer() {
    scene.remove(mesh);
    mesh.geometry.dispose();
}

```

After having loaded the files, and closing my viewer I never seem to be able to release the memory used to load the files.

I've tried to NOT add the decoded geometry  to my THREE.js scene, just to try to rule out that the problem is with THREE.js. Memory is still not released. 
I tried to `dispose`  geometry and destroy all the draco objects DRACOLoader.js' `convertDracoGeometryTo3JS` function:

``` javascript
        convertDracoGeometryTo3JS: function(dracoDecoder, decoder, geometryType,
                                            buffer) {
            if (this.getAttributeOptions('position').skipDequantization === true) {
               decoder.SkipAttributeTransform(dracoDecoder.POSITION);
            }
            .....
            
            // try to destroy the objects
            dracoDecoder.destroy(posTransform);
            dracoDecoder.destroy(decoder);
            dracoDecoder.destroy(dracoGeometry);
            geometry.dispose();
            return null;
```

so my thought is that with the above code, the memory should've been released.  But from taking a memory snapshot with chrome, I get that more then 1GB of memory is still allocated:

![image](https://user-images.githubusercontent.com/1786123/33549253-319e3cd8-d8ea-11e7-9c0d-bde1814572b5.png)

The draco file is aprox: 6MB with 3295950 verts and 3024128 faces
I am using three.js v0.88.0

**Comment by ondys** [comment] 2017-12-04 16:59
Was the `dracoLoader` still allocated at the point you were checking the memory?

As long as the Draco module inside the loader is allocated, it may still hold to the internal memory that was used during decoding

**Comment by simena86** [comment] 2017-12-05 09:10
It probably was. I now tried to do the following to release memory:

``` javascript
dracoLoader = null; 
let element = document.getElementById("decoder_script");
element.parentNode.removeChild(element);
THREE.DRACOLoader.dracoDecoderType = null;
DracoDecoderModule = null;
``` 
without any luck, so maybe some other objects holds references to the allocated data, preventing GC from releasing it from memory? Any other way to de-allocate the Draco module explicitly?

Btw, I'm doing this in a React SPA, so I don't want to re-load the page.

**Comment by simena86** [comment] 2017-12-05 18:29
Created a js fiddle here: https://jsfiddle.net/turbowhale/wbt9gvc7/73/

The mesh takes up 300+ MB, even after the mesh was removed from the scene.

**Comment by ondys** [comment] 2017-12-06 00:03
Thanks, I could reproduce the issue and I'm investigating it.

**Comment by ondys** [comment] 2017-12-13 20:33
This issue should be fixed in our latest release (1.2.4). You can also use a new function `THREE.DRACOLoader.releaseDecoderModule()` to automatically release all data associated with the Draco decoder module without manually deleting the DRACOLoader and other properties

**Comment by simena86** [comment] 2018-01-03 10:48
@ondys: I tried DRACOLoader from version 1.2.4: 
https://jsfiddle.net/turbowhale/wbt9gvc7/90/

Even after calling `THREE.DRACOLoader.releaseDecoderModule()` DRACOLoader still seems to keep 300+ MB of memory allocated. Am I doing something wrong here? In our real life application, DRACOLoader can easily accumulate 2GB+ of memory, causing the browser to crash. Some help is much appreciated :)

**Comment by ondys** [comment] 2018-01-09 17:55
@simena86 I couldn't reproduce the issue on my end (using Chrome 63 on Ubuntu). What browser/OS are you using?

**Comment by simena86** [comment] 2018-01-12 09:28
@ondys sorry this was probably just a false alaram. 

I'm running Ubuntu 16.04 and Chrome 62

If I do the following:

1. Open dev tools
2. load mesh
3. release mesh
4. Record memory from dev tools

then 300+ MB is still allocated

However, if I skip step 1. then, the recording yields 60MB, and everything is fine, so this was probably just a problem with how chrome does GC when dev tools are enabled?

**Comment by simena86** [comment] 2018-01-12 10:40
Hmm, running https://jsfiddle.net/turbowhale/wbt9gvc7/91/ with firefox 56.0 the memory does not seem to be cleared after calling `releaseDecoderModule()`

**Comment by simena86** [comment] 2018-02-08 18:13
@ondys any plans for this in the near future? We're still having problems with large memory leaks causing crashes in our webapp.

**Comment by ondys** [comment] 2018-02-12 18:14
I've been looking into it, but unfortunately I haven't been able to find a solution for the problem yet (on Firefox, it seems to work fine with Chrome). 

Note that the memory doesn't really leak as the it would get re-used if you decode more Draco models. The issue is that Firefox doesn't seem to garbage collect it (at least not immediately, I found out that the memory gets freed if I leave the window open for a long time)

**Comment by hccampos** [comment] 2018-02-12 18:53
Same here. The browser leaves the memory allocated for a while just in case you need it again for something else. Eventually it clears things up. 

The crashes should only occur on allocation if the browser detects too much memory is being allocated too quickly. Mobile browers are especially sensitive to that.

The ideal solution is to load models in chunks as needed rather than loading very large models. Something like Cesium does with its 3D tiles (soon draco-compatible it seems).

**Comment by FrankGalligan** [comment] 2018-08-11 05:48
Closing this issue as the main issue seems to be addressed.

**Closed by FrankGalligan** 2018-08-11 05:48 UTC
