### ISSUE TITLE
1.4 release throws RuntimeError in the browser console

### ISSUE THREAD

**Issue by majksner** [google/draco#653] opened 2020-12-02 13:37 UTC
Hi,

Seems like new release broke my 3d viewer that displays Draco compressed files. Anyone else has this issue?

I'm using https://www.gstatic.com/draco/v1/decoders/* to load *.wasm files.

<img width="1912" alt="Screenshot 2020-12-02 at 14 33 14" src="https://user-images.githubusercontent.com/512355/100879104-54b2fb80-34ab-11eb-9926-80316676aca8.png">

**Comment by FrankGalligan** [comment] 2020-12-02 17:18
Hi @majksner Is this happening with all of your 3d models?

Are you trying to display glTF draco models? Or only draco models (I.e. .drc files)?

**Comment by majksner** [comment] 2020-12-02 17:30
@FrankGalligan it is happening for all my models and they are glTF draco models.

**Comment by FrankGalligan** [comment] 2020-12-02 18:50
I have tested https://threejs.org/examples/?q=gltf#webgl_loader_gltf_extensions with 1.4.0 and I haven't seen any issues.

Do you have a glTF draco file I could try which exhibits the issue?

**Comment by majksner** [comment] 2020-12-02 19:14
Here is the file.

[surfaces.min.zip](https://github.com/google/draco/files/5631487/surfaces.min.zip)

I've also noticed something weird in the response headers from https://www.gstatic.com/draco/v1/decoders/draco_wasm_wrapper.js see image below, especially last-modified header.
![image](https://user-images.githubusercontent.com/512355/100919493-27317680-34da-11eb-83cd-8c701385fc2f.png)

Other file https://www.gstatic.com/draco/v1/decoders/draco_decoder.wasm has yesterday's last-modified date.
![image](https://user-images.githubusercontent.com/512355/100919951-c9515e80-34da-11eb-8c20-8dde99c772a4.png)

**Comment by FrankGalligan** [comment] 2020-12-02 20:46
Hmmm that is weird. Let me try your file.

**Comment by FrankGalligan** [comment] 2020-12-02 21:00
So I tried your file in three.js using 1.4.0 and it rendered. Looked like some kind rainbow sports car.

I also checked the links for draco_decoder.wasm and draco_wasm_wrapper.js from https://www.gstatic.com/draco/v1/decoders/ and it looks like it is serving the correct files.

Can you try clearing your cache and see it that fixes the issue?

Also do yo have link to your website that is public? I could try that as well.

**Comment by donmccurdy** [comment] 2020-12-02 21:08
Do you mind checking this file against three.js with 1.4.0?

[BusterDrone.glb.zip](https://github.com/google/draco/files/5632023/BusterDrone.glb.zip)

I am having trouble with it in a non-three.js loader using 1.4.0, which could easily be my own fault, but it did work in three.js with an older version of Draco.

**Comment by majksner** [comment] 2020-12-02 21:29
@FrankGalligan [here](https://app.airshaper.com/projects/sample/sports-car) is the public link where you can check. I don't think it is a cache problem as I have developer tools open with disabled cache option. I can replicate issue with multiple different devices, iPad, Linux and Mac, Firefox, Safari, Chrome.

Thanks for checking!

**Comment by FrankGalligan** [comment] 2020-12-02 22:14
@majksner I tried your link. I think it worked. I saw the same sports cars but it was blue and red, not rainbow like I saw locally.

**Comment by FrankGalligan** [comment] 2020-12-02 22:19
@donmccurdy I tried your file locally with three.js using 1.4.0 and it worked fine for me. It was some kind of animated three claw drone robot.

**Comment by camnewnham** [comment] 2020-12-02 23:51
We're running into this issue too. Using the airshaper link @majksner posted I found:

Chrome profile 1: Loads correctly
Chrome profile 2: No load (error)
Incognito: No load (error)

Generally profile 1 is used for development so seems likely it would have cached it.

Clearing the cache of profile 1 results in it also no longer loading.

**Comment by adraffy** [comment] 2020-12-03 02:10
Same, all my projects that depended on this are now broken.

**Comment by donmccurdy** [comment] 2020-12-03 02:28
If you're using the evergreen URL hosted on the CDN, you may want to pin the URL to the previous version for now:

- v1.3.6 (old) — `https://www.gstatic.com/draco/versioned/decoders/1.3.6/`
- v1.4.0 (new) - `https://www.gstatic.com/draco/versioned/decoders/1.4.0/`

**Comment by camnewnham** [comment] 2020-12-03 03:46
Thanks @donmccurdy making that change to the draco loader is working for us as a temporary fix.

```
// Preload Draco
const draco = new DRACOLoader()
  .setDecoderPath("https://www.gstatic.com/draco/versioned/decoders/1.3.6/")
  .preload();
```

**Comment by FrankGalligan** [comment] 2020-12-03 06:24
I still cannot reproduce the error on airshaper or elsewhere.

Anyone else have steps I can try?

Thanks

**Comment by majksner** [comment] 2020-12-03 07:24
I think that issue has to do with the CDN caching. For me, it loads draco_wasm_wrapper.js that has a header with the last-modified date of Tue, 03 Mar 2020 16:55:20 GMT which is an old version and then not compatible with the version of draco_encoder.wasm which has the last-modified | Tue, 01 Dec 2020 21:53:06 GMT

See the screenshot below of the diff between version from CDN https://www.gstatic.com/draco/v1/decoders vs one from https://github.com/google/draco/blob/master/javascript/draco_wasm_wrapper.js

<img width="1920" alt="Screenshot 2020-12-03 at 08 17 05" src="https://user-images.githubusercontent.com/512355/100976524-f126dd80-353f-11eb-9319-35a4e9a5e0ff.png">

**Comment by majksner** [comment] 2020-12-03 07:31
Using https://www.gstatic.com/draco/versioned/decoders/1.3.6/ fixes the problem for me as well.

**Comment by FrankGalligan** [comment] 2020-12-03 16:19
Thanks @majksner I will have to see if we can lock the two files form the CDN side when we do an update.

**Comment by willkelleher** [comment] 2020-12-03 17:00
Is it possible to also mention the versioned CDN paths in the documentation? I wasn't aware this was available.

**Comment by Cotterzz** [comment] 2020-12-06 19:38
I think caching is preventing the issue, not causing it, clearing the cache on the problematic machine did nothing, but clearing it on the machine on which it had been working, caused the issue to begin. (as @camnewnham also found)
So replicating it on the machine it wasn't affecting was just a matter of clearing the browsing data manually (browsing history, download history, cookies and cached images/files)
So yeah, caching is a red herring, it sounds as if you're just delivering the wrong combination of wasm and js wrapper, to anyone who's browser hasn't cached those files when the were correctly organised.
(I'm on windows 10 64-bit, chrome and edge, both machines, asking for a specific draco version also fixed it for me)

**Comment by FrankGalligan** [comment] 2020-12-06 19:58
I don't think it is serving the wrong versions. We have had a lot of people
try and we always get the correct version.

Can anyone else try?

Open Chrome developers tools.
Then download both files:
https://www.gstatic.com/draco/v1/decoders/draco_wasm_wrapper.js
https://www.gstatic.com/draco/v1/decoders/draco_decoder.wasm

Then in the network tab you can click on the file and check the
"last-modified" date in the Headers section.

**Comment by Cotterzz** [comment] 2020-12-06 20:55
Clearing cache, and viewing the wasm directly, i still get the one last modified in march.
And like I said, in one case this only happened after i cleared the cache.

**Comment by FrankGalligan** [comment] 2020-12-07 18:04
@Cotterzz I think in the one case you had 1.3.6 unversioned URLs. Then cleared your cache. No you get 1.4.0 for one file and 1.3.6 for the other file. From a proxy that has cached one file and not the other. Most likely base on file type.

**Comment by FrankGalligan** [comment] 2020-12-07 18:09
@majksner Can you try changing your path to https://www.gstatic.com/draco/versioned/decoders/1.4.0/

You shouldn't have a mismatch.

**Comment by majksner** [comment] 2020-12-07 20:40
@FrankGalligan will give it a try tomorrow.

**Comment by majksner** [comment] 2020-12-08 10:32
@FrankGalligan I can confirm that using https://www.gstatic.com/draco/versioned/decoders/1.4.0/ works fine. Both files have the same last-modifed header. Tue, 01 Dec 2020 21:52:04 GMT

**Comment by tomfinegan** [comment] 2021-02-03 20:13
Documentation updates and moving to the versioned URLs seems to have sorted this out. Please reopen this, or open a new issue if there's still a problem.

**Closed by tomfinegan** 2021-02-03 20:13 UTC
